philosophical_topics = [
    "Use of lists in philosophical paradigms",
    "Canonical text on possibilities in Jainism",
    "Dialectical thought and unity of opposites in Plato's Parmenides",
    "Socrates as a \"world-historical person\" and his philosophical thought",
    "Core teaching of Jainism on the persistence and change of existing things",
    "Many-sided objects of knowledge in Jaina thinking",
    "Modal variations in consciousness and absolute knowledge in Jainism",
    "Modifications in the realm of matter and the experiencing states of selves",
    "Mental states and their objects in Socratic dialogues",
    "Socrates",
    "Plato",
    "Aristotle",
    "Dialectical thought and the unity of opposites in Plato's dialogue Parmenides.",
    'Socrates as a "world-historical person" and his philosophical thought.',
    "The varying degrees of validity and soundness in philosophical premises and syllogisms.",
    "The questioning of the presumed soundness and certainty of philosophers' claims.",
    'The distinction between matters of direct observation and the need for proof or demonstration.',
    "The request for additional proof and the king's confusion.",
    'The philosophical significance of inquiries into human psychology.',
    'The verification project and the intuitive nature of philosophical propositions.',
    'The epistemological process in the knowableness of God.',
    'The doctrine of the ground of the soul by Dietrich of Freiberg and Meister Eckhart.'
]